# Generated by Django 4.2.7 on 2025-10-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflowauditlog",
            new_name="workflows_w_instanc_59f4f9_idx",
            old_name="workflows_w_instance__4b7b5e_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowauditlog",
            new_name="workflows_w_event_t_8e484d_idx",
            old_name="workflows_w_event_t_9f7b5b_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowauditlog",
            new_name="workflows_w_timesta_bb6f7e_idx",
            old_name="workflows_w_timesta_5b7b5b_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowauditlog",
            new_name="workflows_w_user_id_46e3eb_idx",
            old_name="workflows_w_user_id_5b7b5b_idx",
        ),
        migrations.RenameIndex(
            model_name="workflownotification",
            new_name="workflows_w_recipie_75db23_idx",
            old_name="workflows_w_recipie_4b7b5e_idx",
        ),
        migrations.RenameIndex(
            model_name="workflownotification",
            new_name="workflows_w_instanc_829df0_idx",
            old_name="workflows_w_instanc_4b7b5e_idx",
        ),
        migrations.RenameIndex(
            model_name="workflownotification",
            new_name="workflows_w_is_sent_e3302f_idx",
            old_name="workflows_w_is_sent_4b7b5e_idx",
        ),
        migrations.RenameIndex(
            model_name="workflownotification",
            new_name="workflows_w_next_es_3e5171_idx",
            old_name="workflows_w_next_es_4b7b5e_idx",
        ),
        migrations.AlterField(
            model_name="workflowauditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workflownotification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
