# Generated by Django 4.2.7 on 2025-10-20 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "workflows",
            "0002_rename_workflows_w_instance__4b7b5e_idx_workflows_w_instanc_59f4f9_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("time_based", "Time Based"),
                            ("event_based", "Event Based"),
                            ("condition_based", "Condition Based"),
                        ],
                        max_length=20,
                    ),
                ),
                ("instance_type", models.CharField(max_length=100)),
                (
                    "time_delay_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "time_delay_field",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "condition_field",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "condition_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("equals", "Equals"),
                            ("not_equals", "Not Equals"),
                            ("greater_than", "Greater Than"),
                            ("less_than", "Less Than"),
                            ("contains", "Contains"),
                            ("not_contains", "Does Not Contain"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("transition", "State Transition"),
                            ("notification", "Send Notification"),
                            ("escalation", "Escalate Priority"),
                            ("assignment", "Auto Assign"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
    ]
