# Generated by Django 5.1.2 on 2025-09-25 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("tenants", "0002_tenant_current_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique payment reference number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="mpesa",
                        help_text="Payment method used",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference (e.g., M-Pesa transaction ID)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current payment status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, help_text="Date payment was made", null=True
                    ),
                ),
                (
                    "processed_date",
                    models.DateTimeField(
                        blank=True, help_text="When payment was processed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional payment notes", null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Payment description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External transaction identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "processor_response",
                    models.TextField(
                        blank=True,
                        help_text="Response from payment processor",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Room payment is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="properties.room",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant making the payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_number"], name="payments_pa_payment_a0847d_idx"
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="payments_pa_referen_c54e4c_idx",
                    ),
                    models.Index(
                        fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_pa_status_7ad4af_idx"
                    ),
                    models.Index(
                        fields=["payment_date"], name="payments_pa_payment_1d6e55_idx"
                    ),
                    models.Index(
                        fields=["tenant"], name="payments_pa_tenant__f6b2cf_idx"
                    ),
                ],
            },
        ),
    ]
