# Generated by Django 4.2.7 on 2025-09-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="rental_agreement",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated rental agreement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="rentals.rentalagreement",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["rental_agreement"], name="payments_pa_rental__88a38b_idx"
            ),
        ),
    ]
