# Generated by Django 5.1.2 on 2025-09-25 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("tenants", "0002_tenant_current_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agreement_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique agreement reference number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Agreement start date")),
                ("end_date", models.DateField(help_text="Agreement end date")),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Monthly rent amount", max_digits=10
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Security deposit amount",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        help_text="Current agreement status",
                        max_length=20,
                    ),
                ),
                (
                    "notice_given_date",
                    models.DateField(
                        blank=True, help_text="Date when notice was given", null=True
                    ),
                ),
                (
                    "notice_period_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Notice period in days"
                    ),
                ),
                (
                    "special_terms",
                    models.TextField(
                        blank=True, help_text="Special terms and conditions", null=True
                    ),
                ),
                (
                    "security_deposit_returned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether security deposit has been returned",
                    ),
                ),
                (
                    "security_deposit_return_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when security deposit was returned",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        help_text="Room being rented",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_agreement",
                        to="properties.room",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="Tenant party to the agreement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_agreement",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agreement_number"],
                        name="rentals_ren_agreeme_f0aa21_idx",
                    ),
                    models.Index(
                        fields=["status"], name="rentals_ren_status_55b3ee_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="rentals_ren_start_d_9c5f9d_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="rentals_ren_end_dat_8496cd_idx"
                    ),
                    models.Index(
                        fields=["tenant"], name="rentals_ren_tenant__7e9858_idx"
                    ),
                    models.Index(
                        fields=["room"], name="rentals_ren_room_id_08d2b4_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(end_date__gt=models.F("start_date")),
                        name="end_date_after_start_date",
                    ),
                    models.CheckConstraint(
                        check=models.Q(rent_amount__gt=0),
                        name="rent_amount_positive",
                    ),
                    models.CheckConstraint(
                        check=models.Q(deposit_amount__gte=0),
                        name="deposit_amount_non_negative",
                    ),
                ],
            },
        ),
    ]
