# Generated by Django 4.2.7 on 2025-09-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_remove_room_current_tenant_and_more"),
        ("tenants", "0002_tenant_current_location"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalagreement",
            name="room",
            field=models.ForeignKey(
                help_text="Room being rented",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_agreements",
                to="properties.room",
            ),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant party to the agreement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_agreements",
                to="tenants.tenant",
            ),
        ),
    ]
