# Generated by Django 5.1.2 on 2025-09-25 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("tenants", "0002_tenant_current_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique maintenance request reference number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title describing the maintenance issue",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the maintenance issue"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level of the maintenance request",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the maintenance request",
                        max_length=20,
                    ),
                ),
                (
                    "requested_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the maintenance was requested",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled date for maintenance work",
                        null=True,
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when maintenance was completed",
                        null=True,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost of maintenance work",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual cost incurred for maintenance",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Technician or staff assigned to the request",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        blank=True, help_text="When the request was assigned", null=True
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about how the issue was resolved",
                        null=True,
                    ),
                ),
                (
                    "resolution_photos",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of photo URLs showing before/after",
                        null=True,
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, help_text="Whether follow-up is required"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateTimeField(
                        blank=True, help_text="Date for follow-up check", null=True
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(
                        blank=True, help_text="Notes from follow-up visit", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Room where maintenance is needed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="properties.room",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant who reported the issue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["request_number"], name="maintenance_request_e2a50e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="maintenance_status_0773c2_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="maintenance_priorit_ec7e12_idx"
                    ),
                    models.Index(
                        fields=["requested_date"], name="maintenance_request_7c15ef_idx"
                    ),
                    models.Index(
                        fields=["scheduled_date"], name="maintenance_schedul_c5df1b_idx"
                    ),
                    models.Index(
                        fields=["completed_date"], name="maintenance_complet_a85e5c_idx"
                    ),
                    models.Index(
                        fields=["tenant"], name="maintenance_tenant__63a485_idx"
                    ),
                    models.Index(
                        fields=["room"], name="maintenance_room_id_8a6701_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="maintenance_created_a408dc_idx"
                    ),
                ],
            },
        ),
    ]
