# Generated by Django 4.2.7 on 2025-10-17 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_remove_room_current_tenant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0002_tenant_current_location"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the request",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="room",
            field=models.ForeignKey(
                help_text="Room where maintenance is needed",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_requests",
                to="properties.room",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant who reported the issue",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_requests",
                to="tenants.tenant",
            ),
        ),
    ]
