# Generated by Django 4.2.7 on 2025-10-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0003_maintenancerequest_feedback_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="documents",
            field=models.JSONField(
                blank=True,
                help_text="JSON array of document URLs attached to the request",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="photos",
            field=models.JSONField(
                blank=True,
                help_text="JSON array of photo URLs attached to the request",
                null=True,
            ),
        ),
    ]
