# Generated by Django 4.2.7 on 2025-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0004_maintenancerequest_documents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="documents",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of document URLs attached to the request",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="photos",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of photo URLs attached to the request",
                null=True,
            ),
        ),
    ]
