# Generated by Django 5.1.2 on 2025-09-25 10:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the tenant", max_length=200
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address",
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="National ID number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact phone",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tenant_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("professional", "Professional"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of tenant",
                        max_length=20,
                    ),
                ),
                (
                    "institution_employer",
                    models.CharField(
                        blank=True,
                        help_text="Institution or employer name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "tenant_status",
                    models.CharField(
                        choices=[
                            ("prospective", "Prospective"),
                            ("active", "Active"),
                            ("former", "Former"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="prospective",
                        help_text="Current tenant status",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("warning", "Warning"),
                            ("violation", "Violation"),
                        ],
                        default="compliant",
                        help_text="Compliance status",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_notes",
                    models.TextField(
                        blank=True, help_text="Notes about compliance status", null=True
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current account balance",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated user account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_status"], name="tenants_ten_tenant__9f2550_idx"
                    ),
                    models.Index(
                        fields=["compliance_status"],
                        name="tenants_ten_complia_7e9938_idx",
                    ),
                    models.Index(
                        fields=["tenant_type"], name="tenants_ten_tenant__af6352_idx"
                    ),
                    models.Index(fields=["name"], name="tenants_ten_name_87437c_idx"),
                    models.Index(fields=["email"], name="tenants_ten_email_4879df_idx"),
                ],
            },
        ),
    ]
