# Generated by Django 5.1.2 on 2025-09-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="current_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Current location/building",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants",
                to="properties.location",
            ),
        ),
    ]
