# Generated by Django 4.2.7 on 2025-10-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_tenant_current_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="compliance_status_changed",
            field=models.DateField(
                blank=True,
                help_text="Date when compliance status last changed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="violation_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of violations recorded for this tenant"
            ),
        ),
    ]
