# Generated by Django 4.2.7 on 2025-10-17 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("cleaner", "Cleaner"),
                            ("caretaker", "Caretaker"),
                            ("maintenance", "Maintenance Technician"),
                            ("security", "Security Guard"),
                        ],
                        default="caretaker",
                        help_text="Staff role/position",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique employee identification number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department or section", max_length=100
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, help_text="Date staff member was hired", null=True
                    ),
                ),
                (
                    "is_active_staff",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this staff member is currently active",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, help_text="Emergency contact person", max_length=255
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact phone number",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__full_name"],
                "indexes": [
                    models.Index(fields=["role"], name="accounts_st_role_784d61_idx"),
                    models.Index(
                        fields=["employee_id"], name="accounts_st_employe_fbf29e_idx"
                    ),
                    models.Index(
                        fields=["is_active_staff"],
                        name="accounts_st_is_acti_9807db_idx",
                    ),
                ],
            },
        ),
    ]
