# Generated by Django 4.2.7 on 2025-10-18 19:21

from django.db import migrations


def update_existing_full_names(apps, schema_editor):
    """Update existing users' full_name fields based on first_name + last_name"""
    User = apps.get_model('accounts', 'User')

    for user in User.objects.all():
        if user.first_name or user.last_name:
            user.full_name = f"{user.first_name} {user.last_name}".strip()
            user.save(update_fields=['full_name'])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_staff"),
    ]

    operations = [
        migrations.RunPython(update_existing_full_names),
    ]
