# Generated by Django 4.2.7 on 2025-09-26 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="current_tenant",
        ),
        migrations.RemoveField(
            model_name="room",
            name="deposit_amount",
        ),
        migrations.RemoveField(
            model_name="room",
            name="rent_amount",
        ),
    ]
