# Generated by Django 4.2.7 on 2025-10-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_staff"),
        ("properties", "0002_remove_room_current_tenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Location manager/caretaker",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_locations",
                to="accounts.staff",
            ),
        ),
    ]
