# Generated by Django 5.1.2 on 2025-09-25 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Report title", max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial Report"),
                            ("occupancy", "Occupancy Report"),
                            ("maintenance", "Maintenance Report"),
                            ("tenant", "Tenant Report"),
                            ("revenue", "Revenue Report"),
                            ("collection", "Collection Report"),
                            ("property", "Property Report"),
                        ],
                        help_text="Type of report",
                        max_length=20,
                    ),
                ),
                (
                    "filters_used",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters used to generate this report",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                        ],
                        default="json",
                        help_text="Format of the exported report",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Generated report file",
                        null=True,
                        upload_to="reports/%Y/%m/",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of report data",
                        null=True,
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False, help_text="Whether report generation is complete"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this report expires and can be deleted",
                        null=True,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        help_text="User who generated the report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type"], name="reports_gen_report__e6102c_idx"
                    ),
                    models.Index(
                        fields=["export_format"], name="reports_gen_export__977178_idx"
                    ),
                    models.Index(
                        fields=["is_complete"], name="reports_gen_is_comp_55c91e_idx"
                    ),
                    models.Index(
                        fields=["generated_by"], name="reports_gen_generat_354594_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="reports_gen_expires_a93554_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Report template name", max_length=200),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial Report"),
                            ("occupancy", "Occupancy Report"),
                            ("maintenance", "Maintenance Report"),
                            ("tenant", "Tenant Report"),
                            ("revenue", "Revenue Report"),
                            ("collection", "Collection Report"),
                            ("property", "Property Report"),
                        ],
                        help_text="Type of report this template generates",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description", null=True
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Template configuration (filters, fields, formatting)",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default filter values for this template",
                    ),
                ),
                (
                    "available_formats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available export formats for this template",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template for its type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["report_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["report_type"], name="reports_rep_report__f68e8c_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="reports_rep_is_acti_4b0ce5_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="reports_rep_is_defa_5d5bcb_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="reports_rep_created_285929_idx"
                    ),
                ],
            },
        ),
    ]
